# Generated by Django 4.2.1 on 2023-05-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, max_length=120, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Название продукта')),
                ('slug', models.SlugField(blank=True, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание продукта')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продукта')),
                ('in_stock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='Категория')),
            ],
        ),
    ]
